version: '2'

services:
  vertx-web:
    image: 'freepsw/vertx-java-var'
    volumes:
      - ~/apps/docker-vertx-mariadb/verticle_data:/usr/verticles
    ports:
      - 8082
    links:
      - 'some-mariadb'
    depends_on:
      - 'some-mariadb'

  some-mariadb:
    image: 'mariadb'
    command: mysqld --innodb-buffer-pool-size=20M
    volumes:
      - "~/apps/docker-vertx-mariadb/verticle_data/dump:/docker-entrypoint-initdb.d"
    environment:
      - "MYSQL_DATABASE=test_db"
      - "MYSQL_USER=root"
      - "MYSQL_ROOT_PASSWORD=my-secret-pw"
    ports:
      - "3306:3306"

  lb:
    image: dockercloud/haproxy
    depends_on:
      - 'vertx-web'
    links:
      - 'vertx-web'
    ports:
      - '8082:80'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
