# Extend vert.x image
FROM vertx/vertx3

# set the verticle class name and the jar file
ENV VERTICLE_NAME io.vertx.blog.first.MyFirstVerticle

# Set the location of the verticles
ENV VERTICLE_HOME /usr/verticles
ENV CLASSPATH $VERTICLE_HOME/mariadb-java-client-1.5.5.jar:$VERTICLE_HOME/my-first-app-db-1.0-SNAPSHOT-fat.jar

EXPOSE 8082

# Launch the verticle
# -cp : set classpath of jar file
WORKDIR $VERTICLE_HOME
ENTRYPOINT ["sh", "-c"]
CMD ["exec vertx run $VERTICLE_NAME --conf $VERTICLE_HOME/my-application-conf.json"]
